12 collapsible sidepanes for visualisation page
nlp-tlp/15926-4-RDL-CITS3200 pull request #18
Opened 2024-08-25 11:22 UTC by ShuaiShao20010902

Completed the task of two collapsible sidepanes on the left and right. Clicking on them will expand and display other options, and clicking again will shrink them back. There are selection bars for text1-text8 in two sidepanes, clicking on them will take you to separate pages

2024-08-28 14:56 UTC, sellsol requested changes
As described in the review comment - let's go with the behaviour of the right sidepane, which doesn't change the cursor while hovering over the non-icon parts of the header. Could you also just lower the font sizes of the headers pls - only as big as the text in the nav links. Other than that the behaviour of the right sidepane now looks fine.

2024-08-28 14:56 UTC, sellsol commented on src/client/src/components/GraphSearchSidepane.vue
Much of the css comments in this file and for the other sidepane are unnecessary. The css is not complicated and is already self-explanatory - remove the comments. Other than that there are slight differences in the css between the right and left sidepanes. Just compare the two side by side in VSCode and make sure they act the same way.

2024-08-28 14:56 UTC, sellsol commented on src/client/src/components/GraphSearchSidepane.vue
> +    </button>
Is the entire header a button? Only the icon is triggering anyway - seems like we're making the whole width a button, then manually changing it so that only the icon bit behaves as a button, which is a bit redundant. Is there a reason you've got this or is this a remnant of the code we wanted removed before

2024-08-29 07:35 UTC, sellsol approved these changes

2024-08-29 07:47 UTC, keyman015 approved these changes
Looks all good, that transition bug is now fixed.

2024-08-29 07:50 UTC, merged