Branch 3 - Initial landing page UI
nlp-tlp/15926-4-RDL-CITS3200 pull request #45
Opened 2024-08-29 18:22 UTC by vinita254

Updated landing page content and styling. 
Once group confirms that page (layout and or content) looks fine, will add background picture possibly a little before week 7 or during week 7.

2024-08-30 14:29 UTC, keyman015 requested changes
Looking good so far, just had some comments about the images in general.

2024-08-30 14:29 UTC, keyman015 commented on src/client/src/views/Landing Page Background.jpg
Is this used in the source code at all? If not, could it please be removed to reduce clutter.

2024-08-30 14:29 UTC, keyman015 commented on src/client/src/views/UWA Logo.png
Could all these images added be moved to `../public/imgs/` (probably even `../public/icons/` for better sorting of icons) to keep them in one location and not with the main pages.

2024-08-30 14:29 UTC, keyman015 commented on src/client/src/views/HomeView.vue
> +    </section>
Could these logos be properly mirrored as they look uneven currently. (minor issue)

2024-08-30 14:29 UTC, keyman015 commented on src/client/src/views/Landing Page Background.jpg
Sorry, just saw your message about adding it later. Ignore this.

2024-09-11 17:06 UTC, vinita254 commented on src/client/src/views/UWA Logo.png
Sure - images have now been moved to ../public/images...

2024-09-11 17:07 UTC, vinita254 commented on src/client/src/views/HomeView.vue
> +    </section>
Done. Please let me know if they still look uneven. Thanks.

2024-09-11 17:56 UTC, keyman015 commented on src/client/src/views/Landing Page Background.jpg
The background image needs to be removed if its not used. (currently isnt referenced/used anywhere)

2024-09-11 17:59 UTC, keyman015 approved these changes
Looks good. Minor issue about logo placing but it can be overlooked for later. There was mention of the background image not working properly, that can be fixed in later issue.

2024-09-12 06:59 UTC, keyman015 approved these changes

2024-09-13 15:27 UTC, keyman015 approved these changes
LGTM

2024-09-14 06:17 UTC, merged