7 set up frontend testing framework
nlp-tlp/15926-4-RDL-CITS3200 pull request #46
Opened 2024-08-30 09:28 UTC by sellsol

### Description
Set up a testing directory for frontend unit tests, and add a testing process into the Github workflow so that code that doesn't pass these tests cannot be merged into main. Write one or two very basic ones just to be sure they work (at your discretion).  

### To-do
- [x] Set up frontend testing framework
- [x] Write one or two basic unit tests
- [x] Integrate into Github workflow
- [x] Update Readme for documentation

### Notes
* The file name of the backend tests have changed so there's a new workflow in GitHub Actions under the same name. Will just have to delete the old one from GitHub once all the branches are migrated over
* Only way to get tsconfig to work properly from the root directory of the repo is to have one in the root directory. I'm not sure what the other tsconfigs do, if they break because of this change let me know. But this was what I had to do to get paths working in tests.  
* Playwright config is autogenerated
* Changed the sidepane header text to only show on v-if, for easier testing - honestly this was what was supposed to be done. That file will need a little rewrite later to decouple the sidepane and the button so we can just not render the sidepane. Out of scope for this ticket. 
* Vitest is needed for unit tests, Playwright is needed for e2e tests. Can't really use one for the other

2024-08-30 14:21 UTC, keyman015 requested changes
This looks amazing, however just some minor comments about documentation and configuration files.

2024-08-30 14:21 UTC, keyman015 commented on src/client/tsconfig.json
> +  "extends": "../../tsconfig.base.json"
I feel the file should be changed to

```
{
  "extends": "./../../tsconfig.base.json",
  "files": [],
  "references": [
    { "path": "./tsconfig.node.json" },
    { "path": "./tsconfig.app.json" }
  ]
}
```
to ensure nothing breaks.

2024-08-30 14:21 UTC, keyman015 commented on README.md
> +```
Should the user be warned to install play-wright and its dependencies as thats separate from the main packages?

2024-09-10 13:27 UTC, sellsol commented on README.md
> +```
Playwright and dependencies get installed on `npm i` right? We have that earlier on. Let me know if not

2024-09-10 16:30 UTC, keyman015 commented on README.md
> +```
for me that was a separate install command i had to run, however it did prompt me properly when i tried to run it pretty sure

2024-09-10 16:35 UTC, keyman015 commented on README.md
> +```
Im happy to mark this as resolved.

2024-09-10 16:36 UTC, keyman015 approved these changes
LGTM

2024-09-11 11:46 UTC, merged