48 some minor js docs and styling fixes
nlp-tlp/15926-4-RDL-CITS3200 pull request #49
Opened 2024-09-01 19:32 UTC by paulmmaingi

### Description
Fix some minor issues in the JSDocs and add some for the icon components. Fix some minor styling issues related to the app container and the side-pane/navbar components.

- [x] JSDocs for Icon components
- [x] Fix navbar and side-panes detaching from each other in smaller displays
![image](https://github.com/user-attachments/assets/35978e92-500d-4bf9-86b0-c1f5ad6e118e)

- [x] Fix side-pane component props
- [x] Fix main app container width restrictions
![image](https://github.com/user-attachments/assets/0e212c61-f961-4366-ae9f-ab5c641429a8)

### Notes
In the Graph view, the display width will have to be adjusted (made reactive) to take into account expanded/collapsed side-panes.

### Linked issues
Closes #48

2024-09-06 12:35 UTC, keyman015 requested changes
Looks amazing. Just found one bug when decreasing the window size on the side panels.

2024-09-06 12:35 UTC, keyman015 commented on src/client/src/components/GraphInfoSidepane.vue
>  .right-sidepanel {
![image](https://github.com/user-attachments/assets/102a6342-ccaf-4fda-97d7-45daa5599e54)

It seems that the window can shrunk to the point that the side panels can interfere. I don't think this is intended behavior.

2024-09-06 14:47 UTC, paulmmaingi commented on src/client/src/components/GraphInfoSidepane.vue
>  .right-sidepanel {
It did seem like making the side-panels reactive was out of the scope of this PR since we'd also have to decide whether or not and how to display what will be contained in the side-panels (search bar, info of classes, toggles) when the display reaches a certain minimum size.

2024-09-07 08:22 UTC, keyman015 commented on src/client/src/components/GraphInfoSidepane.vue
>  .right-sidepanel {
Ah. My bad, didn't realise it was out of the scope. LGTM then.

2024-09-07 08:22 UTC, keyman015 approved these changes

2024-09-07 09:59 UTC, merged