64 search api endpoint
nlp-tlp/15926-4-RDL-CITS3200 pull request #78
Opened 2024-09-22 06:09 UTC by keyman015

## Description
The API endpoint used for searching has been added, allowing users to search using IDs/URIs on `/search/id/(id)` or their label on `/search/label/(label)`. These routes also support attributes of `dep=True/False` to restrict deprecated items in the search results and `limit=(number >= 0)` to limit the return results.

![image](https://github.com/user-attachments/assets/51719df9-b244-4334-abae-268e817b4350)

Results return with an item's deprecation status, id and label for each display.

## Completed To-do List
* [x] Simple string search for uri or label to serve (id, label)
* [x] Search for either field using url parameters, filtering by deprecated if parameter given

## Misc
Closes #64

2024-09-22 08:40 UTC, sellsol requested changes
Code duplication. Looks good otherwise though

2024-09-22 08:40 UTC, sellsol commented on src/server/app/routes.py
You could have the uri/label search be in the same endpoint so the code isn't duplicated like this, you just need to make the search string and field be query parameters as well.

2024-09-22 17:13 UTC, keyman015 commented on src/server/app/routes.py
Yes, this is a very good point. I shall fix this.

2024-09-23 03:54 UTC, sellsol approved these changes

2024-09-23 04:30 UTC, merged