31 search functionality
nlp-tlp/15926-4-RDL-CITS3200 pull request #79
Opened 2024-09-24 03:54 UTC by ShuaiShao20010902

## To-do
Based on the type dropdown and search string in the search sidepane, get the most relevant results in a dropdown underneath the searchbar that can be clicked to select the node in the graph view. 

- [x] Search by id / uri
![image](https://github.com/user-attachments/assets/54b7d2a3-0037-45ff-bf71-f6aec5942aaf)
- [x] Search by label
![image](https://github.com/user-attachments/assets/b494560c-6f70-43d1-83cd-96d91d28da54)

## Linked issues
Closes #31

2024-09-24 04:11 UTC, keyman015 requested changes

2024-09-24 04:11 UTC, keyman015 commented on src/client/src/components/GraphSearchSidepane.vue
> +          <div v-if="showResults && results.length > 0" class="search-results">
Would it be possible to to make the results window smaller than the search panel? It looks rather cramped as it currently stands.

![image](https://github.com/user-attachments/assets/296cb9f3-2192-4367-9cda-c1c82ff911ff)

2024-09-24 04:11 UTC, keyman015 commented on src/client/src/components/GraphSearchSidepane.vue
> +            <ul>
Can the unordered list indentation be removed to increase the space given to the results. The margin between results is enough to differentiate between items.

2024-09-24 04:18 UTC, ShuaiShao20010902 commented on src/client/src/components/GraphSearchSidepane.vue
> +          <div v-if="showResults && results.length > 0" class="search-results">
oh, you mean to make the result window smaller than the search bar right?

2024-09-24 04:20 UTC, keyman015 commented on src/client/src/components/GraphSearchSidepane.vue
> +          <div v-if="showResults && results.length > 0" class="search-results">
No i mean the width of the result popup window should be smaller than the info sidepane's width

2024-09-24 04:22 UTC, ShuaiShao20010902 commented on src/client/src/components/GraphSearchSidepane.vue
> +          <div v-if="showResults && results.length > 0" class="search-results">
oh, that make sense

2024-09-24 04:24 UTC, ShuaiShao20010902 commented on src/client/src/components/GraphSearchSidepane.vue
> +          <div v-if="showResults && results.length > 0" class="search-results">
After modify that, I will show the pic here. Thanks

2024-09-24 04:24 UTC, ShuaiShao20010902 commented on src/client/src/components/GraphSearchSidepane.vue
> +            <ul>
and I will show the pic that removed the unordered list indentation and increse the space on here

2024-09-24 05:48 UTC, ShuaiShao20010902 commented on src/client/src/components/GraphSearchSidepane.vue
> +          <div v-if="showResults && results.length > 0" class="search-results">
![image](https://github.com/user-attachments/assets/d66addf8-3057-4a73-8311-6b7690738917)
how about that now, should I change it smaller?

2024-09-24 18:22 UTC, keyman015 commented on src/client/src/components/GraphSearchSidepane.vue
> +          <div v-if="showResults && results.length > 0" class="search-results">
That looks good thanks

2024-09-24 18:23 UTC, keyman015 approved these changes
LGTM

2024-09-25 12:00 UTC, paulmmaingi approved these changes
LGTM. 
As discussed, debounce time can be adjusted based on feedback from client. (search limits too)

2024-09-25 12:09 UTC, merged