34 local hierarchy
nlp-tlp/15926-4-RDL-CITS3200 pull request #98
Opened 2024-10-10 19:28 UTC by paulmmaingi

### Description
The local hierarchy for any searched node has been implemented. The global and local views have been merged into 1 double sided graph that draws forward for children and backwards for parents. Default view/view on first instance is the root node of the graph, but the search functionality allows access to any local node hierarchy. Levels up and down have been dropped due to the use of dynamic expansion on loading both the children and parent hierarchies.  Separate colours denote varying nodes on the graph, i.e. expandable, root, deprecated, parent, child.

### To-do's Completed

>* [x] Get local hierarchy data from read-many endpoint
>* [x] Render local hierarchy in graph view on select, full RDL on deselect - both views are now 1
>* [ ] Render only hierarchy levels contained in the level filter inputs - this has been dropped
>* [x] Deprecation indicator in information sidepane
>* [x] Deprecation indicator in main graph view

### Linked Issues

Closes #37 
Closes #34

2024-10-11 10:56 UTC, keyman015 commented on src/client/src/components/GraphSearchSidepane.vue
> +              <input type="checkbox" class="mr-2" v-model="deprecatedToggle" />
The search window is not affected by the deprecation toggle, would it be possible to update the API route to have `dep={'true' or 'false'}` using the deprecatedToggle variable?

2024-10-11 10:57 UTC, keyman015 commented on src/client/src/views/GraphView.vue
>    <div class="container">
Can `class="container"` be removed as it causes the visual bug on the graphing view with the invisible bar blocking the graph.

2024-10-11 16:05 UTC, paulmmaingi commented on src/client/src/components/GraphSearchSidepane.vue
> +              <input type="checkbox" class="mr-2" v-model="deprecatedToggle" />
Will be fixed on a new branch so as to get local hierarchy in asap

2024-10-11 16:10 UTC, keyman015 approved these changes
If you're leaving the search to another PR thats fine.

2024-10-12 11:54 UTC, sellsol requested changes

2024-10-12 11:54 UTC, sellsol commented on src/client/src/assets/apiFunctions.ts
> +    // console.log('Node has no children:', node)
stray console.log

2024-10-12 11:54 UTC, sellsol commented on .husky/pre-commit
> -. venv/bin/activate
Would the previous one not have worked for Windows? Would just like to know. Just seems like dealing with compatibility would be a hassle

2024-10-12 14:13 UTC, sellsol approved these changes

2024-10-12 14:14 UTC, merged